# Generated by Django 5.2.3 on 2025-06-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
